# Generated by Django 4.0.4 on 2023-06-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donor', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(upload_to='mosaic')),
            ],
            options={
                'verbose_name': 'Mosaic donor',
                'verbose_name_plural': 'Mosaic donors',
            },
        ),
    ]
