# Generated by Django 4.0.4 on 2023-07-04 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_screenleaves'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChristmasLandingPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_image', models.ImageField(upload_to='christmas_landing_page')),
            ],
            options={
                'verbose_name': 'Christmas landing page donor',
                'verbose_name_plural': 'Christmas landing page donors',
            },
        ),
    ]
