# Generated by Django 4.0.4 on 2023-07-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_christmaslandingpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='christmaslandingpage',
            old_name='donor_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='christmaslandingpage',
            old_name='donor_name',
            new_name='name',
        ),
    ]
