# Generated by Django 4.0.4 on 2023-07-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_rename_donor_image_christmaslandingpage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='christmaslandingpage',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('m', 'medium'), ('l', 'large')], default='s', max_length=1),
        ),
    ]
