# Generated by Django 4.0.4 on 2023-07-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_christmaslandingpage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='christmaslandingpage',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
