# Generated by Django 4.0.4 on 2023-07-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_alter_christmaslandingpage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('team', models.CharField(choices=[('cat', 'cat'), ('dog', 'dog')], default='cat', max_length=3)),
            ],
            options={
                'verbose_name': 'Cat Dog donor',
                'verbose_name_plural': 'Cat Dog donors',
            },
        ),
    ]
