# Generated by Django 4.0.4 on 2023-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_catdog'),
    ]

    operations = [
        migrations.AddField(
            model_name='catdog',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
