# Generated by Django 4.0.4 on 2023-07-24 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_catdog_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('end_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('enable', models.BooleanField(default=False)),
                ('value', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
