# Generated by Django 4.0.4 on 2023-07-24 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0009_setting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='end_date',
            new_name='date',
        ),
    ]
