# Generated by Django 4.0.4 on 2023-07-24 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0011_rename_enable_setting_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='date',
        ),
        migrations.AddField(
            model_name='setting',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
