# Generated by Django 4.0.4 on 2023-09-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0014_pinata_delete_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinata',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
