# Generated by Django 4.0.4 on 2023-09-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0015_alter_pinata_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinata',
            name='team',
            field=models.CharField(choices=[('team1', 'TEAM 1'), ('team2', 'TEAM 2'), ('team3', 'TEAM 3')], default='cat', max_length=5),
        ),
    ]
