# Generated by Django 4.0.4 on 2023-09-05 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0016_pinata_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinataTeam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pinata',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.pinatateam'),
        ),
    ]
