# Generated by Django 4.0.4 on 2023-09-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0017_pinatateam_alter_pinata_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitStar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
