# Generated by Django 4.0.4 on 2023-09-13 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0018_bitstar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BitStar',
            new_name='BigStar',
        ),
    ]
