# Generated by Django 4.0.4 on 2023-09-13 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0019_rename_bitstar_bigstar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigstar',
            options={'verbose_name': 'Big star donor', 'verbose_name_plural': 'Big star donors'},
        ),
        migrations.AlterModelOptions(
            name='pinata',
            options={'verbose_name': 'Pinata donor', 'verbose_name_plural': 'Pinata donors'},
        ),
    ]
